import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar/navbar'
import Footer from '@/components/Footer/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Obidjon',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-slate-600">
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  )
}
